#!/usr/bin/env python3
"""
MQTT server for M-TEC Energybutler reading modbus data
(c) 2023 by Christian Rödel 
"""
from config import cfg
from datetime import datetime
import logging
import time
import signal
import MTECmodbusAPI

try:
  import paho.mqtt.client as mqttcl
  import paho.mqtt.publish as publish
except Exception as e:
  logging.warning("MQTT not set up because of: {}".format(e))

run_status = True  

#----------------------------------
def signal_handler(signal_number, frame):
  global run_status
  logging.warning('Received Signal {}. Graceful shutdown initiated.'.format(signal_number))
  run_status = False
    
# ============ MQTT ================
def on_mqtt_connect(mqttclient, userdata, flags, rc):
  logging.info("Connected to MQTT broker")

def on_mqtt_message(mqttclient, userdata, message):
  try:
    msg = message.payload.decode("utf-8")
    topic = message.topic.split("/")
  except Exception as e:
    logging.warning("Error while handling MQTT message: {}".format(str(e)))

def mqtt_start(): 
  try: 
    client = mqttcl.Client()
    client.username_pw_set(cfg['MQTT_LOGIN'], cfg['MQTT_PASSWORD']) 
    client.connect(cfg['MQTT_SERVER'], cfg['MQTT_PORT'], keepalive = 60) 
    client.on_connect = on_mqtt_connect
    client.on_message = on_mqtt_message
    client.loop_start()
    logging.info('MQTT server started')
    return client
  except Exception as e:
    logging.warning("Couldn't start MQTT: {}".format(str(e)))
    return None

def mqtt_stop(client):
  try: 
    client.loop_stop()
    logging.info('MQTT server stopped')
  except Exception as e:
    logging.warning("Couldn't stop MQTT: {}".format(str(e)))

def mqtt_publish( topic, payload ):
  if not cfg['MQTT_DISABLE']:  
    auth = {
      'username': cfg['MQTT_LOGIN'],
      'password': cfg['MQTT_PASSWORD'] 
    }  
    logging.debug("Publish MQTT command {}: {}".format(topic, payload))
    try:
      publish.single(topic, payload=payload, hostname=cfg['MQTT_SERVER'], port=cfg['MQTT_PORT'], auth=auth)
    except Exception as e:
      logging.error("Could't send MQTT command: {}".format(str(e)))

# =============================================

# read data from MTEC modbus
def read_MTEC_data( registers ):
  now = datetime.now()
  data = MTECmodbusAPI.read_modbus_data(ip_addr=cfg['MODBUS_IP'], port=cfg['MODBUS_PORT'], 
                                        slave=cfg['MODBUS_SLAVE'], registers=registers)
  pvdata = {}
  try:
    pvdata["api_date"] = now.strftime("%Y/%m/%d %H:%M:%S") # Local time of this server
    pvdata["inverter_date"] = data["10100"]               # Time from inverter
    pvdata["inverter_status"] = data["10105"]             # Inverter status
 
    pvdata["current_PV"] = data["11028"]                  # Current power flow from PV
    pvdata["current_grid"] = data["11000"]                # Current power flow from/to grid
    pvdata["current_battery"] = data["30258"]             # Current power flow from/to battery
    pvdata["current_inverter"] = data["11016"]            # Current power flow from/to inverter
    pvdata["current_backup"] = data["30230"]              # Current backup power flow
    pvdata["current_consumption"] = data["11016"]["value"] - data["11000"]["value"]  # Current power consumption 
    pvdata["current_battery_SOC"] = data["33000"]         # Current battery SOC

    pvdata["day_PV"] = data["31005"]                      # Energy generated by PV today
    pvdata["day_grid_feed"] = data["31000"]               # Energy feed to grid today
    pvdata["day_grid_purchase"] = data["31001"]           # Energy purchased from grid today
    pvdata["day_battery_charge"] = data["31003"]          # Energy charged to battery total
    pvdata["day_battery_discharge"] = data["31004"]       # Energy discharged from battery total
    pvdata["day_consumption"] = data["31005"]["value"] + data["31001"]["value"] + data["31004"]["value"] - data["31000"]["value"] - data["31003"]["value"]  # Current power consumption 
    pvdata["day_autarky_rate"] = 100*(1 - (data["31001"]["value"] / pvdata["day_consumption"])) if pvdata["day_consumption"]>0 else 0 
    pvdata["day_own_consumption_rate"] = 100*(1-data["31000"]["value"] / data["31005"]["value"]) if data["31005"]["value"]>0 else 0
      
    pvdata["total_PV"] = data["31112"]                    # Energy generated by PV total
    pvdata["total_grid_feed"] = data["31102"]             # Energy feed to grid total
    pvdata["total_grid_purchase"] = data["31104"]         # Energy purchased from grid total
    pvdata["total_battery_charge"] = data["31108"]        # Energy charged to battery total
    pvdata["total_battery_discharge"] = data["31110"]     # Energy discharged from battery total
    pvdata["total_consumption"] = data["31112"]["value"] + data["31104"]["value"] + data["31110"]["value"] - data["31102"]["value"] - data["31108"]["value"]  # Current power consumption 
    pvdata["total_autarky_rate"] = 100*(1 - (data["31104"]["value"] / pvdata["total_consumption"])) if pvdata["total_consumption"]>0 else 0
    pvdata["total_own_consumption_rate"] = 100*(1-data["31102"]["value"] / data["31112"]["value"]) if data["31112"]["value"]>0 else 0

  except Exception as e:
    logging.warning("Retrieved Modbus data is incomplete: {}".format(str(e)))
  return pvdata

# write data to MQTT
def write_to_MQTT( pvdata, base_topic ):
  for param, data in pvdata.items():
    topic = base_topic + param
    if isinstance(data, dict):
      if isinstance(data["value"], float):  
        payload = cfg['MQTT_FLOAT_FORMAT'].format( data["value"] )
      elif isinstance(data["value"], bool):  
        payload = "{:d}".format( data["value"] )
      else:
        payload = data["value"]
    else:   
      if isinstance(data, float):  
        payload = cfg['MQTT_FLOAT_FORMAT'].format( data )
      elif isinstance(data, bool):  
        payload = "{:d}".format( data )
      else:
        payload = data  
    logging.info("- {}: {}".format(topic, str(payload)))
    mqtt_publish( topic, payload )

#==========================================
def main():
  global run_status

  # Initializaion
  signal.signal(signal.SIGTERM, signal_handler)
  signal.signal(signal.SIGINT, signal_handler)
  logging.basicConfig()
  if cfg['DEBUG'] == True:
    logging.getLogger().setLevel(logging.DEBUG)
  logging.info("Starting")

  registers = [ '10100', '10105', '11028', '11000', '30258', '11016', '30230', '33000', 
               '31000', '31001', '31003', '31004', '31005', '31102', '31104', '31108', '31110', '31112' ]
  mqttclient = mqtt_start()

  while run_status: # and mqttclient
    pvdata = read_MTEC_data(registers=registers)
    if pvdata:
      write_to_MQTT( pvdata, cfg['MQTT_TOPIC'] + '/' )
    logging.debug("Sleep {}s".format( cfg['POLL_FREQUENCY'] ))
    time.sleep(cfg['POLL_FREQUENCY'])

  mqtt_stop(mqttclient)
  logging.info("Stopped")

if __name__ == '__main__':
  main()
